// Decompiled with JetBrains decompiler
// Type: StudioForge.TotalMiner.BlockMaterial
// Assembly: StudioForge.TotalMiner.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: F0E1DDE7-D62D-405E-BA66-AD2EA8491117
// Assembly location: D:\SteamLibrary\steamapps\common\Total Miner\StudioForge.TotalMiner.API.dll

namespace StudioForge.TotalMiner
{
  public enum BlockMaterial : byte
  {
    None,
    Clay,
    Sandstone,
    Limestone,
    Basalt,
    Andesite,
    Dacite,
    Diorite,
    Tuff,
    Serpentine,
    Gabbro,
    Granite,
    Komatiite,
    Marble,
    Rhyolite,
    Bedrock,
    Flint,
    Copper,
    Cassiterite,
    Coal,
    Iron,
    Gold,
    Opal,
    Carbon,
    Sulphur,
    Cyclonite,
    Fluorite,
    Platinum,
    Greenstone,
    Diamond,
    Sapphire,
    Ruby,
    Titanium,
    Obsidian,
    Uranium,
    Composite,
    SoftComposite,
    Glass,
    FramedGlass,
    Stick,
    Wood,
    Leaves,
    Earth,
    Sand,
    Porous,
    Snow,
    Crop,
    Vegetation,
    Vapor,
    Liquid,
    Fire,
    Ice,
    Paper,
    Brick,
    Stone,
    Metal,
    Explosive,
    Key,
    Fibre,
    Color,
    SpiderEgg,
    Barrier,
    zLastID,
  }
}
