// Decompiled with JetBrains decompiler
// Type: StudioForge.TotalMiner.ItemSoundGroup
// Assembly: StudioForge.TotalMiner.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: F0E1DDE7-D62D-405E-BA66-AD2EA8491117
// Assembly location: D:\SteamLibrary\steamapps\common\Total Miner\StudioForge.TotalMiner.API.dll

namespace StudioForge.TotalMiner
{
  public enum ItemSoundGroup : ushort
  {
    None,
    Base,
    BodyHit,
    EnvCaveIn,
    EnvExplosion,
    EnvNightfall,
    GenPickup,
    GuiAccept,
    GuiCancel,
    GuiInvalid,
    GuiMoveCursor,
    GuiSelect,
    GuiTransfer,
    GuiGamerJoined,
    GuiTxtMsgIn,
    ItemActivate,
    ItemArmor,
    ItemBlock,
    ItemBow,
    ItemCooked,
    ItemCrop,
    ItemDiamantiumTool,
    ItemDiamondTool,
    ItemWoodDoor,
    ItemMetalDoor,
    ItemEarth,
    ItemFire,
    ItemFlora,
    ItemGem,
    ItemGlass,
    ItemGrass,
    ItemGreenstoneTool,
    ItemIronTool,
    ItemJewelry,
    ItemKey,
    ItemLava,
    ItemLeather,
    ItemMetal,
    ItemOre,
    ItemPorous,
    ItemPortcullis,
    ItemRareTool,
    ItemRaw,
    ItemRock,
    ItemRope,
    ItemRubyTool,
    ItemSand,
    ItemShield,
    ItemSkill,
    ItemSnow,
    ItemSteelTool,
    ItemStone,
    ItemTile,
    ItemTitaniumTool,
    ItemTree,
    ItemWater,
    ItemWood,
    ItemWoodTool,
    ItemWool,
    ItemGun,
    ItemGunSMG,
    ItemGunLaser,
    zLast,
  }
}
