// Decompiled with JetBrains decompiler
// Type: StudioForge.Engine.GamerServices.GamerPresenceMode
// Assembly: StudioForge.Engine.GamerServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 3EA07B8F-6C00-417B-9E82-CD1E4EB140B6
// Assembly location: D:\SteamLibrary\steamapps\common\Total Miner\StudioForge.Engine.GamerServices.dll

namespace StudioForge.Engine.GamerServices
{
  public enum GamerPresenceMode
  {
    ArcadeMode,
    AtMenu,
    BattlingBoss,
    CampaignMode,
    ChallengeMode,
    ConfiguringSettings,
    CoOpLevel,
    CoOpStage,
    CornflowerBlue,
    CustomizingPlayer,
    DifficultyEasy,
    DifficultyExtreme,
    DifficultyHard,
    DifficultyMedium,
    EditingLevel,
    ExplorationMode,
    FoundSecret,
    FreePlay,
    GameOver,
    InCombat,
    InGameStore,
    Level,
    LocalCoOp,
    LocalVersus,
    LookingForGames,
    Losing,
    Multiplayer,
    NearlyFinished,
    None,
    OnARoll,
    OnlineCoOp,
    OnlineVersus,
    Outnumbered,
    Paused,
    PlayingMinigame,
    PlayingWithFriends,
    PracticeMode,
    PuzzleMode,
    ScenarioMode,
    Score,
    ScoreIsTied,
    SettingUpMatch,
    SinglePlayer,
    Stage,
    StartingGame,
    StoryMode,
    StuckOnAHardBit,
    SurvivalMode,
    TimeAttack,
    TryingForRecord,
    TutorialMode,
    VersusComputer,
    VersusScore,
    WaitingForPlayers,
    WaitingInLobby,
    WastingTime,
    WatchingCredits,
    WatchingCutscene,
    Winning,
    WonTheGame,
  }
}
